<?php

namespace Proxies\__CG__\Projet\Symfony2Bundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Candidat extends \Projet\Symfony2Bundle\Entity\Candidat implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Projet\\Symfony2Bundle\\Entity\\Candidat' . "\0" . 'idCandidat', '' . "\0" . 'Projet\\Symfony2Bundle\\Entity\\Candidat' . "\0" . 'prenom', '' . "\0" . 'Projet\\Symfony2Bundle\\Entity\\Candidat' . "\0" . 'nom', '' . "\0" . 'Projet\\Symfony2Bundle\\Entity\\Candidat' . "\0" . 'numCin', '' . "\0" . 'Projet\\Symfony2Bundle\\Entity\\Candidat' . "\0" . 'email', '' . "\0" . 'Projet\\Symfony2Bundle\\Entity\\Candidat' . "\0" . 'numTel', '' . "\0" . 'Projet\\Symfony2Bundle\\Entity\\Candidat' . "\0" . 'adresse', '' . "\0" . 'Projet\\Symfony2Bundle\\Entity\\Candidat' . "\0" . 'dateDeNaissance', '' . "\0" . 'Projet\\Symfony2Bundle\\Entity\\Candidat' . "\0" . 'password', '' . "\0" . 'Projet\\Symfony2Bundle\\Entity\\Candidat' . "\0" . 'idAutoEcole');
        }

        return array('__isInitialized__', '' . "\0" . 'Projet\\Symfony2Bundle\\Entity\\Candidat' . "\0" . 'idCandidat', '' . "\0" . 'Projet\\Symfony2Bundle\\Entity\\Candidat' . "\0" . 'prenom', '' . "\0" . 'Projet\\Symfony2Bundle\\Entity\\Candidat' . "\0" . 'nom', '' . "\0" . 'Projet\\Symfony2Bundle\\Entity\\Candidat' . "\0" . 'numCin', '' . "\0" . 'Projet\\Symfony2Bundle\\Entity\\Candidat' . "\0" . 'email', '' . "\0" . 'Projet\\Symfony2Bundle\\Entity\\Candidat' . "\0" . 'numTel', '' . "\0" . 'Projet\\Symfony2Bundle\\Entity\\Candidat' . "\0" . 'adresse', '' . "\0" . 'Projet\\Symfony2Bundle\\Entity\\Candidat' . "\0" . 'dateDeNaissance', '' . "\0" . 'Projet\\Symfony2Bundle\\Entity\\Candidat' . "\0" . 'password', '' . "\0" . 'Projet\\Symfony2Bundle\\Entity\\Candidat' . "\0" . 'idAutoEcole');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Candidat $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdCandidat()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdCandidat();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdCandidat', array());

        return parent::getIdCandidat();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenom($prenom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenom', array($prenom));

        return parent::setPrenom($prenom);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenom', array());

        return parent::getPrenom();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom($nom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', array($nom));

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', array());

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumCin($numCin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumCin', array($numCin));

        return parent::setNumCin($numCin);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumCin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumCin', array());

        return parent::getNumCin();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', array($email));

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', array());

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumTel($numTel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumTel', array($numTel));

        return parent::setNumTel($numTel);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumTel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumTel', array());

        return parent::getNumTel();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresse($adresse)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresse', array($adresse));

        return parent::setAdresse($adresse);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresse', array());

        return parent::getAdresse();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateDeNaissance($dateDeNaissance)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateDeNaissance', array($dateDeNaissance));

        return parent::setDateDeNaissance($dateDeNaissance);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateDeNaissance()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateDeNaissance', array());

        return parent::getDateDeNaissance();
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword($password)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', array($password));

        return parent::setPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', array());

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdAutoEcole($idAutoEcole)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdAutoEcole', array($idAutoEcole));

        return parent::setIdAutoEcole($idAutoEcole);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdAutoEcole()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdAutoEcole', array());

        return parent::getIdAutoEcole();
    }

}
