Epreuve:
    type: entity
    table: epreuve
    id:
        idEpreuve:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: id_epreuve
            generator:
                strategy: IDENTITY
    fields:
        nomEpreuve:
            type: string
            nullable: false
            length: 20
            fixed: false
            comment: ''
            column: nom_epreuve
    lifecycleCallbacks: {  }
