ResponsableAutoEcole:
    type: entity
    table: responsable_auto_ecole
    uniqueConstraints:
        email:
            columns:
                - email
    id:
        idResponsableAutoEcole:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: id_responsable_auto_ecole
            generator:
                strategy: IDENTITY
    fields:
        prenom:
            type: string
            nullable: false
            length: 20
            fixed: false
            comment: ''
        nom:
            type: string
            nullable: false
            length: 20
            fixed: false
            comment: ''
        numCin:
            type: string
            nullable: false
            length: 8
            fixed: false
            comment: ''
            column: num_cin
        email:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
        numTel:
            type: string
            nullable: false
            length: 8
            fixed: false
            comment: ''
            column: num_tel
        password:
            type: string
            nullable: false
            length: 20
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
