<?php

namespace Proxies\__CG__\Projet\Symfony2Bundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Notification extends \Projet\Symfony2Bundle\Entity\Notification implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Projet\\Symfony2Bundle\\Entity\\Notification' . "\0" . 'idNotification', '' . "\0" . 'Projet\\Symfony2Bundle\\Entity\\Notification' . "\0" . 'expediteur', '' . "\0" . 'Projet\\Symfony2Bundle\\Entity\\Notification' . "\0" . 'lu', '' . "\0" . 'Projet\\Symfony2Bundle\\Entity\\Notification' . "\0" . 'idRdv', '' . "\0" . 'Projet\\Symfony2Bundle\\Entity\\Notification' . "\0" . 'idRdvTemp');
        }

        return array('__isInitialized__', '' . "\0" . 'Projet\\Symfony2Bundle\\Entity\\Notification' . "\0" . 'idNotification', '' . "\0" . 'Projet\\Symfony2Bundle\\Entity\\Notification' . "\0" . 'expediteur', '' . "\0" . 'Projet\\Symfony2Bundle\\Entity\\Notification' . "\0" . 'lu', '' . "\0" . 'Projet\\Symfony2Bundle\\Entity\\Notification' . "\0" . 'idRdv', '' . "\0" . 'Projet\\Symfony2Bundle\\Entity\\Notification' . "\0" . 'idRdvTemp');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Notification $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdNotification()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdNotification();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdNotification', array());

        return parent::getIdNotification();
    }

    /**
     * {@inheritDoc}
     */
    public function setExpediteur($expediteur)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExpediteur', array($expediteur));

        return parent::setExpediteur($expediteur);
    }

    /**
     * {@inheritDoc}
     */
    public function getExpediteur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExpediteur', array());

        return parent::getExpediteur();
    }

    /**
     * {@inheritDoc}
     */
    public function setLu($lu)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLu', array($lu));

        return parent::setLu($lu);
    }

    /**
     * {@inheritDoc}
     */
    public function getLu()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLu', array());

        return parent::getLu();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdRdv($idRdv)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdRdv', array($idRdv));

        return parent::setIdRdv($idRdv);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdRdv()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdRdv', array());

        return parent::getIdRdv();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdRdvTemp($idRdvTemp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdRdvTemp', array($idRdvTemp));

        return parent::setIdRdvTemp($idRdvTemp);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdRdvTemp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdRdvTemp', array());

        return parent::getIdRdvTemp();
    }

}
