services:
#    projet_symfony2.example:
#        class: Projet\Symfony2Bundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
# [...] Vos autres services
    redirect.after.login:
        class: MyApp\UserBundle\Redirection\AfterLoginRedirection
        arguments: [@router]